#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
DATA_DIRECTORY="moodledata"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
DATADIR_PATH="${PROJECT_ROOT}/${DATA_DIRECTORY}"
WWW_ROOT="http://moodle.docksal"
ADMIN_PASS="Admin1234#"
ADMIN_EMAIL="admin@moodle.docksal"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

composer_install ()
{
	cd "$PROJECT_ROOT/web"
	echo-green "Installing dependencies..."
	composer install
}

# Install site
site_install ()
{
	cd "$DOCROOT_PATH"

	echo-green "Installing Moodle..."
  /usr/local/bin/php admin/cli/install.php \
  --non-interactive=true \
  --lang=en --wwwroot=${WWW_ROOT} \
  --dataroot=${DATADIR_PATH} \
  --dbtype=mariadb \
  --dbhost=db \
  --dbname=default \
  --dbuser=${MYSQL_USER} \
  --dbpass=${MYSQL_PASSWORD} \
  --adminpass=${ADMIN_PASS} \
  --fullname="My Moodle" \
  --shortname="Moodle" \
  --agree-license=true \
  --adminemail=${ADMIN_EMAIL}

}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
time -p composer_install
time -p site_install

echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."
echo -e "Admin user: ${yellow}admin"
echo -e "Admin pass: ${yellow}${ADMIN_PASS}"
echo-yellow "Look for admin login credentials in the output above."

#-------------------------- END: Execution --------------------------------
